### ISSUE TITLE
missing npm install in documentation

### ISSUE THREAD

**Issue by l-vincent-l** [catalogueglobal/datatools-ui#10]
you need to run `npm install` before `$ mastarm build --config /path/to/configurations/dir` if you want to build the ui

**Comment by landonreed** [comment]
That's right @l-vincent-l.  Typically we will run with `npm start`, which will run `yarn` as a prestart.  The build script assumes the packages have ben installed already.

**Comment by landonreed** [comment]
Closing due to staleness.
