### ISSUE TITLE
Toggling between Snapshots within Editor does not automatically update current data 

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#101]
When using the bottom-right shortcut bar to switch between snapshots, a page refresh is required to actually see the new snapshot's data.

**Comment by landonreed** [comment]
The above commit only partially fixes the issue.  If a snapshot is restored while viewing a pattern or the timetable editor, we get an infinite spinner.  This seems to be because the patterns have not yet been fetched.
