### ISSUE TITLE
Adding/Deleting stops in Pattern Causes Alignment to Draw Incorrectly

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#105]
1. Create a new pattern
2. Add three stops
3. Delete stops 2 and 3
4. Add a new, different 2nd stop
5. Blue Line will draw as bidirectional:
<img width="408" alt="image" src="https://user-images.githubusercontent.com/653100/39544567-7cc469d8-4e1c-11e8-9f3b-51565c70f002.png">
Line is wonky from that point forward

**Comment by landonreed** [comment]
Related to this: when deleting a pattern stop, it appears that control points between the deleted stop and other remaining pattern stops are not always deleted/cleaned up nicely.

**Comment by landonreed** [comment]
This hasn't been entirely fixed, but the behavior is improved somewhat in the `pattern-fixes` branch
