### ISSUE TITLE
Delete Pattern Button Sometimes Enabled w/ no Patterns

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#106]
Noticing this specifically after performing steps for #105

If pattern being edited is only pattern in route, after deleting pattern the "delete pattern" trash can button will stay enabled. Clicking it causes error:

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/653100/39544673-ccaeff3a-4e1c-11e8-8dbc-f5d55d60433f.png">

**Comment by landonreed** [comment]
I'm having trouble recreating this, even when following the steps in #105.

**Comment by demory** [comment]
Appears to have been fixed by work on #105
