### ISSUE TITLE
Viewing manage account shows a "Feed Source ID does not exist" error

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#122]
This happens on the current test server with my demory@conveyal.com account

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/653100/39763734-eff2224a-52ab-11e8-8431-4918799acb23.png">

**Comment by landonreed** [comment]
This is due to subscriptions in the user profile to feed sources that no longer exist.  Rather than showing the error message, the requests should just silently fail.
