### ISSUE TITLE
Pattern Editor: Add stop to middle of pattern doesn't work

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#128]
From an empty pattern, add two stops. Then add a third stops as the 2nd stop (via the add-stop drowdown > "insert as stop 2"). The newly added stop becomes the last stop, which is not the expected behavior:

<img width="276" alt="image" src="https://user-images.githubusercontent.com/653100/39786422-8c9dae1a-52ee-11e8-84a5-c25015b39532.png">

<img width="440" alt="image" src="https://user-images.githubusercontent.com/653100/39786456-a9c1848a-52ee-11e8-950e-ab749a018d85.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/653100/39786472-bce981a2-52ee-11e8-946c-40dfe5c23272.png">

(The stops should go 1 to 3, left to right)

**Comment by landonreed** [comment]
Adding stop to beginning of pattern is also not working.
