### ISSUE TITLE
Trips do not order based off of differences in arrival time.

### ISSUE THREAD

**Issue by evansiroky** [catalogueglobal/datatools-ui#169]
If all times are the same except for the arrival time, the trips will not be secondarily sorted based off of arrival time.

**Comment by landonreed** [comment]
It probably makes sense to sort by `arrival_time` and not departures, no?  We could first sort by the first stop time's `arrival_time` and then secondarily by trip ID.  Are there even cases when multiple trips for a pattern would have the same first arrival time?

**Comment by evansiroky** [comment]
I was just playing around with the timetable editor and noticed this behavior.  I'm not sure how the sorting algorithm works, but it seems like it'd make sense to sort by arrival_time then departure_time of each stop_time.
