### ISSUE TITLE
Refactor messages

### ISSUE THREAD

**Issue by evansiroky** [catalogueglobal/datatools-ui#201]
The current way of getting messages could be refactored in a way that utilizes a connected component to retrieve the message string from.

**Comment by evansiroky** [comment]
@landonreed what are your thoughts on refactoring the way messages are retrieved.  It's a bit cumbersome to say `getMessage(this.messages, 'path.path')` each time in the components.  What if instead we refactored the `getComponentMessages` function to return a function as follows:

```javascript
function getComponentMessages (componentName: string): string => string {
  const componentMessages = (
    objectPath.get(window.DT_CONFIG, ['messages', 'active', 'components', componentName]) ||
    {}
  )
  return (path: string) => {
    const message = objectPath.get(componentMessages, path)
    return typeof message === 'string' ? message : `{${path}}`
  }
}
```

That way, the new method of getting a message would be as follows: 

```javascript
this.messages('path.path')
```

**Comment by landonreed** [comment]
Yea, that's great!

**Comment by evansiroky** [comment]
See #247 for messages refactor

**Comment by evansiroky** [comment]
#247 has been merged into dev.  Closing.
