### ISSUE TITLE
DateTime selector dropdown not clickable

### ISSUE THREAD

**Issue by landonreed** [catalogueglobal/datatools-ui#261]
On staging, the date time selector (for example, in the QC view or editing GTFS calendars) popup is not clickable. You can click the calendar icon to have the popup appear, but it is not registering hover or click events.  This doesn't appear to be happening if I run the same code locally.

**Comment by evansiroky** [comment]
Not quite sure how it happened, but the css in staging does not look like what is in the css in the actual node_modules of the react-bootstrap-datetimepicker.  Maybe a rm -rf node_modules and redeploy might work?

**Comment by landonreed** [comment]
Thanks for looking into this. `rm -rf node_modules` doesn't seem to work though.
