### ISSUE TITLE
On Auth0 login errorfetching user data

### ISSUE THREAD

**Issue by a1ex4nd3r** [catalogueglobal/datatools-ui#268]
Hi,

Im not sure if it's the same issue as #70 . 
Im using the dev branch and when I login I am getting this:
[Screen1](http://prntscr.com/lq0qss) and it's redirecting back to main page. I configured Auth0 user account as in the docs. Any suggestions?

**Comment by landonreed** [comment]
Did you follow the instructions in this note about new Auth0 accounts? Also, the server side error is likely to give you a better hint at what's going wrong.

https://github.com/catalogueglobal/datatools-ui/blob/885f244dcbfca5604a2299e918ca400d866549ba/docs/dev/deployment.md#L138-L144

**Comment by a1ex4nd3r** [comment]
Thank You, it helped to be able to login to the App. Im still getting this auth  
[error](http://prntscr.com/lqlulk). Cant create project, or upload gtfs, and from time to time Im getting this [message](http://prntscr.com/lqlvim). Anyone had this issue maybe?

**Comment by a1ex4nd3r** [comment]
I fixed the issue with setting directly in env-server.yml the AUTH0 token.
