### ISSUE TITLE
Docker deployment?

### ISSUE THREAD

**Issue by typhoon2099** [catalogueglobal/datatools-ui#68]
Is it possible to deploy this via Docker?

**Comment by landonreed** [comment]
The front end assets can be built using `yarn build`.  The current set up with datatools-server depends on running the server jar which serves these assets hosted on an S3 bucket.  There may be other set ups to bypass this (e.g., serving the assets with nginx and proxying API calls to the server), but none have been configured or tested. 

Closing for now, continue any additional discussion in catalogueglobal/datatools-server#77.
