### ISSUE TITLE
Logged out immediately after logging in

### ISSUE THREAD

**Issue by typhoon2099** [catalogueglobal/datatools-ui#70]
I'm still not sure if I've configured Auth0 correctly. I've checked the Auth0 logs and appear to be getting a failed silent auth on the login page, after which I can log in, but I don't get to do anything before I've been logged out by the frontend. Auth0 logs it as a successful logout.

I notice when I'm on the homepage that /api/manager/public/region returns a 404 (message: Unknown error occurred), could this be causing the frontend to panic and kick me out?

Just to note: I'm using the `auth0-update-sql` branch as I can't get Auth0 to work on the dev branch (hard coded URLs etc).

**Comment by landonreed** [comment]
I believe this should be solved with #250 now.
