### ISSUE TITLE
Pattern geometry slicing/pattern stop shape dist traveled is inaccurate for some patterns

### ISSUE THREAD

**Issue by landonreed** [catalogueglobal/datatools-ui#82]
Patterns found in AC Transit and TriMet routes seem to be sliced incorrectly.  The sliced line segments, which should correspond to the pattern stop locations, are either entirely missing (TriMet) or entirely mismatched (AC Transit).

**Comment by demory** [comment]
Example: https://gtfs-manager-dev.conveyal.com/feed/f317c85a-1258-4c89-981b-47737c29cc3a/edit/route/42/trippattern/738

<img width="475" alt="image" src="https://user-images.githubusercontent.com/653100/39546436-683c3e2c-4e22-11e8-91f1-7050c108ec69.png">

**Comment by landonreed** [comment]
TriMet routes are now working with the above fix!  This was all due to `shape_dist_traveled` values not being represented in meters.  To fix this, we create a scale factor using the last `shape_dist_traveled`, which should be equivalent to the pattern length, and the pattern length in meters.  We then multiply the `shape_dist_traveled` values by the factor any time we need to use them to provide distances in meters (e.g., when we slice up the pattern shape at pattern stops).

![image](https://user-images.githubusercontent.com/2370911/39731956-8ee8317e-5238-11e8-815a-6a3ec398dced.png)
