### ISSUE TITLE
When viewing stops, changing route in route-selection dropdown causes error

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#87]
![image](https://user-images.githubusercontent.com/653100/39497258-85d6bd8e-4d70-11e8-85be-1af8517fa770.png)

1. Go to feed version https://gtfs-manager-dev.conveyal.com/feed/f317c85a-1258-4c89-981b-47737c29cc3a
2. Select 'Routes'
3. Select the first route ("Aub 1..")
4. Select 'View Stops' for the first pattern ("34 stops from...")
5. In 'Filtering Stops for Pattern' dropdown, try switching to the 2nd pattern
6. [ERROR]

**Comment by landonreed** [comment]
This appears to be an issue with the leaflet map where a StopMarker that failed to mount is being updated: https://reactjs.org/docs/error-decoder.html?invariant=136&args[]=StopMarker
