### ISSUE TITLE
Selected "parent_station" in stop does not persist when saved

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#92]
Can select a stop as `parent_station` and it shows up as the value until hitting Save, but then resets to nothing after saving is completed

**Comment by landonreed** [comment]
Note: this commit https://github.com/catalogueglobal/datatools-ui/commit/6e1bcc6bca7f909088200bb1d0a8ea8ccef77b31 has somewhat broken the stop selector, so I need to fix.
