### ISSUE TITLE
Error Editing Feed Info from Deep Link in Fresh Browser Session

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#96]
Steps to reproduce:
1. Navigate to feed info editing, copy current URL (e.g. https://gtfs-manager-dev.conveyal.com/feed/f317c85a-1258-4c89-981b-47737c29cc3a/edit/feedinfo/3)
2. Completely close and restart browser
3. Navigate to copied link. Editing page loads correctly
4. Edit the feed publisher name to something different and try saving
5. Error:

![image](https://user-images.githubusercontent.com/653100/39521404-5c1467aa-4ddc-11e8-837d-bc1bc4336adc.png)

**Comment by landonreed** [comment]
Commit 7effe175df79593073e4d548af45e46d6e3699ba fixes this issue (as well as #99).
