### ISSUE TITLE
Error Uploading Branding Image for Agency

### ISSUE THREAD

**Issue by demory** [catalogueglobal/datatools-ui#98]
Error when trying to upload PNG from computer:

![image](https://user-images.githubusercontent.com/653100/39521949-a3caa4e0-4dde-11e8-8d7e-aea8d3b721e0.png)

Image taken from https://www.centro.org/images/default-source/logos/centro-header-logo-larger.jpg?sfvrsn=0

**Comment by landonreed** [comment]
@demory, can you confirm that this is still occurring for you with the latest commits?  It seems to work fine locally for me.

**Comment by landonreed** [comment]
Fixed in https://github.com/catalogueglobal/datatools-server/commit/cf144d76b7db69690e7030288998aea99ea30f6e and https://github.com/catalogueglobal/datatools-server/commit/6cd9a76b1231944a09961740c9eca3d9dab63459
